services:
  backend:
      image: ghcr.io/xyhelper/claude-api-server:latest
      ports:
        - 8001:8001
      environment:
        - TZ=Asia/Shanghai
        - CLAUDEPROXY=
      volumes:
        - ./backend/manifest:/app/manifest
        - ./config/config.yaml:/app/config.yaml
      restart: unless-stopped
      
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123123"
    restart: unless-stopped

  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/